name: Build on preview environment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: yarn
          node-version: 18

      - name: Install dependencies
        run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Check Tag Duplicity
        run: yarn run dupcheck

      - name: Build project
        run: yarn build --mode development
